= Bases de Datos I: Trabajo Práctico 2
Liz Moreno López <lilita.moreno@hotmail.com>; Micaela Vera <micavera2010@hotmail.com>; Verónica Juarez <veronicajuarez01@hotmail.com>
{docdate}. Docentes Hernán Rondelli y Mariano Trigila (COM-01)
:numbered:
:source-highlighter: highlight.js
:tabsize: 4

El presente documento consiste en describir la aplicación CLI realizada en Go siguiendo el diseño de datos relativo a operaciones de tarjetas de crédito. Dicha aplicacion consiste en el que el usuario pueda realizar las siguientes acciones:

- Autorización de la compra
- Generación de la factura
- Alerta a los clientes


== Introducción

Las tarjetas no permiten a los usuarios financiar una compra en cuotas,
todo se realiza en un solo pago. Una persona puede tener más de una
tarjeta pero no deben existir extensiones de la misma. Las tarjetas
podrán estar expiradas en su fecha de vencimiento.

Las tarjetas tendrán consumos que deben surgir a partir de las compras
que se realicen en los distintos comercios.  También, nos interesan los
datos de los clientes, de las tarjetas de crédito con sus vencimientos y
límites, entre otros. 

A partir de los datos de una compra, se puede aceptar o rechazar dicha
compra. Se debe considerar distintos factores para la autorización de la
compra; debe existir el número de la tarjeta y corresponder a alguna
tarjeta vigente, el código de seguridad tiene que ser el correcto, el
monto total de las compras pendientes de pago más la compra a realizar
no debe superar el límite de compra de la tarjeta, por último, la
tarjeta no debe estar vencida ni suspendida.

Para cada nuevo consumo se deben guardar los datos de una factura con el
nombre y apellido, dirección, número de tarjeta, período de la factura,
fecha de vencimiento, todas las compras del período, y total a pagar.

Por último, se deben generar alertas por posibles fraudes. Existe un
Call Center que ante cada alerta generada automáticamente realiza un
llamado telefónico al cliente, indicándole la alerta detectada y
verifica si se trató de un fraude ó no.  Se debe tener en cuenta para
las alertas:

- Si una tarjeta registra dos compras en un lapso menor de un minuto en comercios distintos ubicados en el mismo código postal.
- Si una tarjeta registra dos compras en un lapso menor de 5 minutos en comercios con diferentes códigos postales.
- Si una tarjeta registra dos rechazos por exceso de límite en el mismo día, la tarjeta tiene que ser suspendida preventivamente.


== Descripción

En esta sección pueden incluirse las dificultades que tuvieron, las
soluciones encontradas, y las decisiones que fueron tomando a lo largo
del trabajo práctico.

También, se debe incluir una descripción general del programa—cómo
funciona.

*(Longitud: 3–5 párrafos)*



== Implementación


=== Autorizacion de la compra
La autorizacion de la compra consiste en recibir los datos de la tarjeta, es decir, el numero de dicha tarjeta y su codigo de seguridad, el numero del comercio y el monto de dicho consumo. Si todos estos datos son correctos, se procedera a autorizar dicha compra,por esto la stored procedure retornara true. En caso de que algun dato sea invalido, devolvera false.
El procedimiento antes de autorizar dicha compra debe cumplir una serie de elementos:
    
    - El numero de la tarjeta debe ser existente, y corresponder a alguna tarjeta vigente.
    En caso de que no cumpla, se debe cargar los datos en la tabla rechazo con el mensaje *?tarjeta no valida o no vigente*.

    - El codigo de seguridad debe ser correcto. 
    En caso de que no cumpla, se debe cargar los datos en la tabla rechazo con el mensaje *?codigo de seguridad invalido*.

    - El monto total de compras pendientes de pago mas la compra a realizar no debe superar el limite de compra de la tarjeta.
    En caso de que no cumpla, se debe cargar los datos en la tabla rechazo con el mensaje *?supera limite de tarjeta*.

    - La tarjeta no debe estar vencida. 
    En caso de que no cumpla, se debe cargar los datos en la tabla rechazo con el mensaje *?plazo de vigencia expirado*.

    - La tarjeta no debe estar suspendida. En caso de que no cumpla ,se debe cargar los datos en la tabla rechazo con el mensaje *?la tarjeta se encuentra suspendida*.

Por esto, como se nombro anteriormente si al menos uno de los parametros es invalido se procedera a insertar los datos de la compra en la tabla rechazo donde se ingresara el numero de la tarjeta, el numero de comercio, el monto, la fecha y el respectivo mensaje del rechazo de dicha compra.

La tabla rechazo posee el siguiente formato:
-
[source,sql]
----
insert into rechazo values (default,nrocomercio, nrocomercio, fecha, monto, motivo)
----

La funcion que nombramos anteriormente, cuyo nombre es autorizacion_compra:

[source,sql]
----
----

En esta sección se incluye el código fuente correctamente formateado—y
comentado, si corresponde. Además, por cada fragmento de código
relevante—i.e. función, método, procedimiento—se debe dar una
descripción general, decir qué hace, y especificar los parámetros que
toma la función/método/procedimiento, junto con los valores que devuelve
ó modifica.

_No debería incluirse el código de librerías/frameworks que se
utilicen—a no ser que sea absolutamente necesario._

*(Longitud: lo que sea necesario)*



== Conclusiones

Aquí van algunas reflexiones acerca del proceso de desarrollo del
trabajo realizado, y de los resultados obtenidos. También se debe
incluir una conclusión final de producto terminado.

Pueden incluirse lecciones aprendidas durante el desarrollo del trabajo.

*(Longitud: 1–3 párrafos)*
